version: '3.9'

networks:
  traefik-net:
    external: true

services:
  frontend:
    image: hamband_volunteer_frontend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.volunteer-fe.rule=Host(`hamband.math.sharif.edu`) && PathPrefix(`/volunteer`)"
        - "traefik.http.routers.volunteer-fe.entrypoints=web-secure"
        - "traefik.http.routers.volunteer-fe.tls=true"
        - "traefik.http.routers.volunteer-fe.tls.certresolver=myresolver"
        - "traefik.http.services.to-volunteer-fe.loadbalancer.server.port=80"
      networks:
        - traefik-net
